version: "3.9"
services:
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wanted
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1